// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductMicroservice.Models;

namespace ProductMicroservice.Migrations
{
    
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductMicroservice.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Budjet Friendly",
                            ImageName = "product1.jpg",
                            Price = 5999.0,
                            ProductName = "Redmi",
                            Rating = 5.0
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Camera Clarity",
                            ImageName = "product2.jpg",
                            Price = 3500.0,
                            ProductName = "Iphone",
                            Rating = 3.0
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Good Proccessor",
                            ImageName = "product3.jpg",
                            Price = 6999.0,
                            ProductName = "Iqoo7",
                            Rating = 4.0
                        },
                        new
                        {
                            ProductId = 4,
                            Description = "Nice Product",
                            ImageName = "product4.jpg",
                            Price = 4599.0,
                            ProductName = "samsung",
                            Rating = 2.0
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Long Life Time",
                            ImageName = "product5.jpg",
                            Price = 2900.0,
                            ProductName = "Nokia",
                            Rating = 5.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
